version: '3.8'

services:
  mediawiki:
    build:
      context: ./mediawiki
      dockerfile: ./Dockerfile
    links:
      - db
    volumes:
      - ./mediawiki/shared:/opt/mediawiki_shared:rw

  db:
    image: mariadb:10
    volumes:
      - ./mariadb/data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mediawiki}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mediawiki}
      MYSQL_USER: ${MYSQL_USER:-mediawiki}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mediawiki}
