version: '3.6'

services:
  mediawiki:
    restart: unless-stopped

  db:
    restart: unless-stopped

  certbot:
    build:
      context: ./certbot
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/letsencrypt:/etc/letsencrypt:rw
    environment:
      - DOMAIN=${DOMAIN}
      - REDIRECT_DOMAIN=${REDIRECT_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    links:
      - mediawiki
    volumes:
      - ./nginx/default.conf:/tmp/default.conf:ro
      - ./nginx/redirect.conf:/tmp/redirect.conf:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/letsencrypt:/etc/letsencrypt:ro
    environment:
      - DOMAIN=${DOMAIN}
      - REDIRECT_DOMAIN=${REDIRECT_DOMAIN}
    depends_on:
      - certbot
    command: /app/start.sh
