version: '3.8'

services:
  mediawiki:
    build:
      context: ./mediawiki
      dockerfile: ./Dockerfile
    links:
      - db
    volumes:
      - ./mediawiki/shared:/opt/mediawiki_shared:rw
    depends_on:
      - db
    environment:
      DOMAIN: ${DOMAIN:?DOMAIN must be set in .env file, eg. DOMAIN=example.org}
      SCHEME: ${SCHEME:-https}
      ADMIN_EMAIL: ${ADMIN_EMAIL:?ADMIN_EMAIL must be set in .env file, eg. ADMIN_EMAIL=admin@example.org}
      INSTALL_WIKI_NAME: ${INSTALL_WIKI_NAME:?INSTALL_WIKI_NAME must be set in .env file, eg. INSTALL_WIKI_NAME=Empire Wiki}
      INSTALL_WIKI_ADMIN_USER: ${INSTALL_WIKI_ADMIN_USER:?INSTALL_WIKI_ADMIN_USER must be set in .env file, eg. INSTALL_WIKI_ADMIN_USER=Admin}
      INSTALL_WIKI_ADMIN_PASSWORD: ${INSTALL_WIKI_ADMIN_PASSWORD:?INSTALL_WIKI_ADMIN_PASSWORD must be set in .env file, eg. INSTALL_WIKI_ADMIN_PASSWORD=admin}
      INSTALL_WIKI_LANG: ${INSTALL_WIKI_LANG:-en}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mediawiki}
      MYSQL_USER: ${MYSQL_USER:-mediawiki}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mediawiki}
    command: sh -c '/root/wait-for -t 60 db:3306 -- /root/start.sh'

  db:
    image: mariadb:10
    volumes:
      - ./mariadb/data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mediawiki}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mediawiki}
      MYSQL_USER: ${MYSQL_USER:-mediawiki}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mediawiki}
